---
title: "EDA"
author: "Raphaël Morsomme"
date: "February 11, 2020"
output: pdf_document
---

```{r}
library(tidyverse)

# See example of how to use my_ggsave() and generate_table in the Model.Rmd file. 
my_ggsave <- partial(ggsave, path = "Deliverables/Figures", width = 5, height = 3.5)

generate_table <- function(d, name = "test.tex", cap = ""){
  d %>%
    xtable(caption= cap) %>%
    print(file= str_c("Deliverables/Figures/", name), type = "latex", booktab = TRUE)
}

source("prettyplot.R")
load("Data/data_model.RDATA")

```


```{r}
pdf("Deliverables/Figures/response.pdf", width = 10, height = 5.2)

par(mfrow=c(1,2), mar=c(3,2,1,1))
hist(d$ressource_need, xlab="Ressource need score", line=1.1, breaks=50)

dat = d[,c("consumption_risk", "behavioural_risk", "situational_risk", "awareness")]
cor.im(dat[complete.cases(dat),], size=1)

dev.off()
```



```{r}

p0 = predict(m0)
Y0 = d0$Y

p1 = predict(m1)
Y1 = d1$Y

L = seq(min(Y0), max(Y0), length.out = 10)
r = sapply(L, function(L) {
  c(mean((p0 < L)[Y0 < L]), mean((p0 > L)[Y0 > L]))

})
plot(r[1,], r[2,])
```


```{r}
pdf("Deliverables/Figures/residuals.pdf", width=8, height=3)

par(mfrow=c(1,2), mar=c(3,2,1,1))

hist(Y0-p0, xlab="Base model residuals", line=1.2, xlim=c(-4,4), breaks=30)
hist(Y1-p1, xlab="Augmented model residuals", line=1.2, xlim=c(-4,4), breaks=30)

dev.off()
```









